export const data = [
  {
    adult: false,
    backdrop_path: "/wwFBRyekDcKXJwP0mImRJjAnudL.jpg",
    genre_ids: [27],
    id: 632357,
    original_language: "en",
    original_title: "The Unholy",
    overview:
      "Alice, a young hearing-impaired girl who, after a supposed visitation from the Virgin Mary, is inexplicably able to hear, speak and heal the sick. As word spreads and people from near and far flock to witness her miracles, a disgraced journalist hoping to revive his career visits the small New England town to investigate. When terrifying events begin to happen all around, he starts to question if these phenomena are the works of the Virgin Mary or something much more sinister.",
    popularity: 3681.658,
    poster_path: "/b4gYVcl8pParX8AjkN90iQrWrWO.jpg",
    release_date: "2021-03-31",
    title: "The Unholy",
    video: false,
    vote_average: 7.2,
    vote_count: 500,
  },
  {
    adult: false,
    backdrop_path: "/gPKcJzrbgs1670fOeKN1xQH9mNa.jpg",
    genre_ids: [80, 18, 9648, 53],
    id: 823855,
    original_language: "en",
    original_title: "I Am All Girls",
    overview:
      "A special crimes investigator forms an unlikely bond with a serial killer to bring down a global child sex trafficking syndicate.",
    popularity: 1941.731,
    poster_path: "/m6bUeV4mczG3z2YXXr5XDKPsQzv.jpg",
    release_date: "2021-05-14",
    title: "I Am All Girls",
    video: false,
    vote_average: 6.9,
    vote_count: 74,
  },
  {
    adult: false,
    backdrop_path: "/iDdpiUnCeXvBmrkBFpL6lKsZt33.jpg",
    genre_ids: [53, 18, 28, 9648],
    id: 578701,
    original_language: "en",
    original_title: "Those Who Wish Me Dead",
    overview:
      "A young boy finds himself pursued by two assassins in the Montana wilderness with a survival expert determined to protecting him - and a forest fire threatening to consume them all.",
    popularity: 1658.204,
    poster_path: "/xCEg6KowNISWvMh8GvPSxtdf9TO.jpg",
    release_date: "2021-05-05",
    title: "Those Who Wish Me Dead",
    video: false,
    vote_average: 7.1,
    vote_count: 307,
  },
];
